services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mys.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./mys:/app
    ports:
      - "8000:8000"
    env_file:
      - ./mys/.env
